name: mv to docs
on: push
jobs:
  mv_to_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |  
          sudo sed -i -e 's@/https@https@' dist/index.html 
          sudo cp dist/index.html docs/index.html
          sudo cp dist/https:/wadda0714.github.io/My_Portfolio/style.css docs/css/style.css 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
